"""orgs table

Revision ID: 76356cd7bf78
Revises: 73f16b418bcc
Create Date: 2019-12-14 21:24:40.229540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76356cd7bf78'
down_revision = '73f16b418bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('pos', sa.String(length=140), nullable=True),
    sa.Column('loc', sa.String(length=140), nullable=True),
    sa.Column('stipend', sa.String(length=140), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_timestamp'), 'org', ['timestamp'], unique=False)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_org_timestamp'), table_name='org')
    op.drop_table('org')
    # ### end Alembic commands ###
